# Default values for cloud-native-postgresql.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: quay.io/enterprisedb/cloud-native-postgresql
  pullPolicy: IfNotPresent
  # -- Overrides the image tag whose default is the chart appVersion.
  tag: "1.3.0"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

webhook:
  mutating:
    create: true
    failurePolicy: Fail
  validating:
    create: true
    failurePolicy: Fail

config:
  create: true
  data: {}
    #INHERITED_ANNOTATIONS: categories
    #INHERITED_LABELS: environment, workload, app
    #EDB_LICENSE_KEY: <YOUR_EDB_LICENSE_KEY_HERE>
  name: postgresql-operator-controller-manager-config

# -- Additinal arguments to be added to the operator's args list
additionalArgs:  []

serviceAccount:
  # -- Specifies whether a service account should be created
  create: true
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

rbac:
  # -- Specifies whether ClusterRole and ClusterRoleBinding should be created
  create: true

# -- Annotations to be added to the pod
podAnnotations: {}
# -- Annotations to be added to all other resources
commonAnnotations: {}

# -- Security Context for the whole pod
podSecurityContext:
  runAsUser: 1001
  # fsGroup: 2000

service:
  type: ClusterIP
  # -- DO NOT CHANGE THE SERVICE NAME as it is currently used to generate the certificate
  # and can not be configured
  name: postgresql-operator-webhook-service
  port: 443

resources: {}
  # If you want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  #
  # limits:
  #   cpu: 100m
  #   memory: 1Gi
  # requests:
  #   cpu: 100m
  #   memory: 100Mi

# -- Nodeselector for the operator to be installed
nodeSelector: {}

# -- Tolerations for the operator to be installed
tolerations: []

# -- Affinity for the operator to be installed
affinity: {}
