{{- if .Values.webhook.mutating.create }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: postgresql-operator-mutating-webhook-configuration
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "cloud-native-postgresql.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-postgresql-k8s-enterprisedb-io-v1-backup
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: mbackup.kb.io
  rules:
  - apiGroups:
    - postgresql.k8s.enterprisedb.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backups
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-postgresql-k8s-enterprisedb-io-v1-cluster
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: mcluster.kb.io
  rules:
  - apiGroups:
    - postgresql.k8s.enterprisedb.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-postgresql-k8s-enterprisedb-io-v1-scheduledbackup
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: mscheduledbackup.kb.io
  rules:
  - apiGroups:
    - postgresql.k8s.enterprisedb.io
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scheduledbackups
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-postgresql-k8s-enterprisedb-io-v1alpha1-backup
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: mbackupv1alpha1.kb.io
  rules:
  - apiGroups:
    - postgresql.k8s.enterprisedb.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - backups
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-postgresql-k8s-enterprisedb-io-v1alpha1-cluster
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: mclusterv1alpha1.kb.io
  rules:
  - apiGroups:
    - postgresql.k8s.enterprisedb.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: {{ .Values.service.name }}
      namespace: {{ .Release.Namespace }}
      path: /mutate-postgresql-k8s-enterprisedb-io-v1alpha1-scheduledbackup
  failurePolicy: {{ .Values.webhook.validating.failurePolicy }}
  name: mscheduledbackupv1alpha1.kb.io
  rules:
  - apiGroups:
    - postgresql.k8s.enterprisedb.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - scheduledbackups
  sideEffects: None
  {{- end }}
