---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    control-plane: controller-manager
    {{- include "cloud-native-postgresql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: webhook-server
    name: webhook-server
  selector:
    control-plane: controller-manager
    {{- include "cloud-native-postgresql.selectorLabels" . | nindent 4 }}
