name: release-publish

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04
    container:
      image: quay.io/helmpack/chart-releaser:v1.2.1
      options: --entrypoint sh

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        env:
          CR_TOKEN: "${{ secrets.REPO_GHA_PAT }}"
        run: |
          repo=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 2)
          owner=$(echo "$GITHUB_REPOSITORY" | cut -d '/' -f 1)
          commit=$(git rev-parse HEAD)
          url="https://$owner.github.io/$repo"
          # upload the chart as release on github
          cr upload --owner "$owner" --git-repo "$repo" --commit "$commit"
          # update the index accordingly on branch gh-pages

          cr index --owner "$owner" --git-repo "$repo" --charts-repo "$url" --push
