name: release-publish

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: quay.io/helmpack/chart-releaser:v1.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        with:
          entrypoint: sh
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        with:
          entrypoint: sh
        env:
          CR_TOKEN: "${{ secrets.REPO_GHA_PAT }}"
        run: |
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")
          commit=$(git rev-parse HEAD)
          # upload the chart as release on github
          cr upload --owner "$owner" --repo "$repo" -c "$commit"
          # update the index accordingly on branch gh-pages
          cr index --owner "$owner" --repo "$repo" -c "$commit" --push