name: release-publish

on:
  push:
    tags:
      - v*

jobs:
  release:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Install Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0

      - name: Run chart-releaser
        env:
          CR_TOKEN: "${{ secrets.REPO_GHA_PAT }}"
          CHART_RELEASER_VERSION: "v1.2.1"
        run: |
          repo=$(cut -d '/' -f 2 <<< "$GITHUB_REPOSITORY")
          owner=$(cut -d '/' -f 1 <<< "$GITHUB_REPOSITORY")

          arch=$(uname -m)
          cache_dir="$RUNNER_TOOL_CACHE/ct/$version/$arch"
          if [[ ! -d "$cache_dir" ]]; then
            mkdir -p "$cache_dir"

            echo "Installing chart-releaser..."
            curl -sSLo cr.tar.gz "https://github.com/helm/chart-releaser/releases/download/$version/chart-releaser_${CHART_RELEASER_VERSION#v}_linux_amd64.tar.gz"
            tar -xzf cr.tar.gz -C "$cache_dir"
            rm -f cr.tar.gz

            echo 'Adding cr directory to PATH...'
            export PATH="$cache_dir:$PATH"
          fi

          cr upload --owner "$owner" --repo "$repo" -c "$(git rev-parse HEAD)"
          cr index --owner "$owner" --repo "$repo" -c "$(git rev-parse HEAD)" --push
